#!/bin/bash
# Some dumb script

echo "hello world"
i=8
echo "the value of \"i\" is $i."

let i=i+5

echo "the value of \"i\" is now $i."

echo -n "values of \"i\" in the loop are: "
for i in 7 8 9 11
do
  echo -n "$i "
done

exit 0
